name: wine2-15
version: 1.0
summary: An experimental wine-2.15 snap
description: Wine-2.15 as an experimental snap
confinement: devmode
grade: stable
architectures: [ amd64 ]

apps:
  notepad:
    command: launcher notepad
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  wine:
    aliases:
    - wine
    command: launcher wine
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  wineserver:
    command: launcher wineserver
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  winecfg:
    command: launcher winecfg
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  regedit:
    command: launcher regedit
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  wineconsole:
    command: launcher wineconsole
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  winefile:
    command: launcher winefile
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]
  winemine:
    command: launcher winemine
    plugs: [ x11, unity7, opengl, home, pulseaudio, hardware-observe, network, network-bind, cups-control ]

parts:
  wine-2.15:
    plugin: autotools
    source: git://source.winehq.org/git/wine.git
    source-depth: 1
    source-tag: wine-2.15
    build-packages:
      - bison
      - desktop-file-utils
      - docbook-to-man
      - docbook-utils
      - docbook-xsl
      - flex
      - fontforge
      - gettext
      - libasound2-dev
      - libcapi20-dev
      - libcups2-dev
      - libdbus-1-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libgif-dev
      - libgl-dev
      - libglu-dev
      - libgnutls-dev
      - libgphoto2-dev
      - libgsm1-dev
      - libjpeg-dev
      - liblcms2-dev
      - libldap2-dev
      - libmpg123-dev
      - libncurses5-dev
      - libopenal-dev
      - libosmesa6-dev
      - libpng12-dev
      - libpulse-dev
      - libsane-dev
      - libtiff-dev
      - libv4l-dev
      - libx11-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxml2-dev
      - libxrandr-dev
      - libxrender-dev
      - libxslt1-dev
      - libxt-dev
      - libxxf86vm-dev
      - linux-kernel-headers
      - ocl-icd-opencl-dev
      - oss4-dev
      - prelink
      - valgrind
      - unixodbc-dev
      - x11proto-xinerama-dev
    stage-packages:
      - libfreetype6
      - fontconfig-config
      - libpng12-0
      - zlib1g
      - libncurses5
      - libgnutls30
  launcher:
    plugin: nil
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp ./launcher $SNAPCRAFT_PART_INSTALL/bin/
    after: [ wine-2.15 ]
